### ISSUE TITLE
[BUG] compilation fails

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist-xqts-runner#13]
I tried to compile exist-xqts-runner as advised in the spec.

Compilation stopped with the following errors:

```
[error] exist-xqts-runner/src/main/scala/org/exist/xqts/runner/AssertTypeParser.scala:96:54: type mismatch;
[error]  found   : Int(7)
[error]  required: org.exist.xquery.Cardinality
[error]           case TypeCardinality.* => ExistCardinality.ZERO_OR_MORE
[error]                                                      ^
[error] exist-xqts-runner/src/main/scala/org/exist/xqts/runner/AssertTypeParser.scala:97:54: type mismatch;
[error]  found   : Int(6)
[error]  required: org.exist.xquery.Cardinality
[error]           case TypeCardinality.+ => ExistCardinality.ONE_OR_MORE
[error]                                                      ^
[error] exist-xqts-runner/src/main/scala/org/exist/xqts/runner/AssertTypeParser.scala:98:54: type mismatch;
[error]  found   : Int(3)
[error]  required: org.exist.xquery.Cardinality
[error]           case TypeCardinality.? => ExistCardinality.ZERO_OR_ONE
[error]                                                      ^
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 42 s, completed Nov 17, 2020 4:36:32 PM
```

- OSX 10.15.7
- sbt installed via homebrew

**Comment by adamretter** [comment]
I am guessing you want to test against eXist-db `5.3.0-SNAPSHOT`? If so, then you need to leave this line as is in `build.sbt`:
```
val existV = "5.3.0-SNAPSHOT"
```

Then before you build the XQTS, you need to checkout the revision of eXist-db `5.3.0-SNAPSHOT` you want to test and build and install the latest artifacts of it. Once those artifacts are installed, you should be able to build and run the XQTS without issue.

**Comment by line-o** [comment]
OK, I obviously did not read the readme thoroughly enough and missed the `val existV = "5.3.0-SNAPSHOT"` part.
How do I install the artifacts?

**Comment by adamretter** [comment]
See the part about "install" in the eXist-db documentation - http://www.exist-db.org/exist/apps/doc/exist-building#build-system

**Comment by line-o** [comment]
For later reference: `mvn clean install -DskipTests=true`

**Comment by line-o** [comment]
The compilation succeeded.
