### ISSUE TITLE
[BUG] Error comparison seems to report false negatives

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist-xqts-runner#15]
In Class XQTS_3_1.xs-base64Binary

case base64-902 is reported as a Failure
Judging from the data this should have been marked as a success instead. FORG0001 was expected and FORG0001 returned.

`Expected: 'Error(FORG0001)', but query returned an error: QueryError(ERROR,exerr:ERROR FORG0001: Invalid base64 data [at line 1, column 1])`

**Comment by line-o** [comment]
Another example in prod-PathExpr

expected `AnyOf(List(Error(XPST0008), Error(XPST0003)))`
actual `QueryError(ERROR,exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 expecting "else", found ']' [at line 1, column 40] )`

marked as Failure

**Comment by line-o** [comment]
There is _a lot_ of those. Fixing this bug alone would give us slightly better overall results.

**Comment by adamretter** [comment]
> Expected: 'Error(FORG0001)', but query returned an error: QueryError(ERROR,exerr:ERROR FORG0001: Invalid base64 data [at line 1, column 1])

This is a bug in eXist-db Error reporting. You can see above `exerr:ERROR` that is the Error Code used by eXist-db when the error code is not known, the `FORG0001` appears as a string within the Error Message returned by eXist-db. This is an eXist-db bug as `FORG0001` should be returned as the Error Code and not (within) the Error Message.
