### ISSUE TITLE
How to handle broken/invalid test cases?

### ISSUE THREAD

**Issue by line-o** [eXist-db/exist-xqts-runner#16]
Inspecting the test results I found at least six test cases using the old map constructor syntax `:=`.
These tests fail now due to an error code mismatch (query throws with XPST0003 instead of FOJS0001)

How can we maintain an updated test suite?

- fn-parse-json-924
- fn-parse-json-925
- fn-parse-json-926
- fn-parse-json-927
- fn-parse-json-928
- fn-parse-json-929

**Comment by line-o** [comment]
from #14 : use  `target/scala-2.13/exist-xqts-runner-assembly-1.0.0.jar -x HEAD` to get the current, maintained testsuite

**Comment by adamretter** [comment]
@line-o running `exist-xqts-runner-assembly-1.0.0.jar --help` will show you all of the options :-p
