### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by joewiz** [eXist-db/exist-xqts-runner#6]
When the test suite runner hits a test that causes eXist to crash, the test suite runner simply stalls. There's no indication that a fatal error has occurred. The current console logging doesn't appear to report what test is about to start. It would be great if there were a better way to determine what tests are causing the runner to stall, so that we could (a) note them and then (b) exclude them from further tests until we're able to address the underlying problems with eXist.

**Comment by adamretter** [comment]
When logging in log4j.xml is set to debug level, progress is now logged to the console, if progress stalls over a period of time a list of outstanding test cases is also logged. Fixed in https://github.com/eXist-db/exist-xqts-runner/pull/9
